// <auto-generated />
namespace FashionShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateDB1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDB1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010061513167_updateDB1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
